apiVersion: v1
kind: ReplicationController
metadata:
  name: catalog
  labels:
    name: catalog
spec:
  replicas: 2
  selector:
    name: catalog
  template:
    metadata:
      labels:
        name: catalog
    spec:
      containers:
      - name: catalog
        image: ajanthan/catalog-ms
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 9090
        readinessProbe:
                  httpGet:
                    path: /healthz
                    port: 9090
                  periodSeconds: 1
                  timeoutSeconds: 1
                  successThreshold: 1
                  failureThreshold: 10